### ISSUE TITLE
[WHEEZY] "packages not installed from repository"

### ISSUE THREAD

**Issue by c0de123** [saltstack/salt-pack#206]
Hi,
there is a problem with the wheezy repository from saltstack.
https://repo.saltstack.com/apt/debian/7/amd64/archive/2016.11.0/
resulted in installing packages in a higher version than it is now:
https://repo.saltstack.com/apt/debian/7/amd64/latest/

The affected packages, at least on my systems, are:
   bsdmainutils (9.0.6)
   libzmq3 (4.0.5+dfsg-3)
   python-jinja2 (2.7.3-1)
   python-msgpack (0.4.2-1)
   python-yaml (3.11-2)

Apparently these versions were never meant to be deployed in the wheezy branch but still, we now have packages not installed from a repository.
Is it planned to be fixed so that the higher versions get pushed into latest again?

**Comment by dmurphy18** [comment]
@c0de123 Yes I see the issue, it appears in the 2016.11.0 release some other than intended versions of packages for Debian 7 happened to be available on the build system, and when apt was used to generate the repository, it picked the latest version as it does.  I shall see if I can update these current packages for Debian 7, since you will not have been the only user affected.

The current versions in latest are the correct intended versions for Debian 7, as of 2016.11.2.  I note the issue also occurred in 2016.11.1.

**Comment by cachedout** [comment]
@dmurphy18  You moved this to the `Done` column so I am closing this. Please let me know if that is a mistake.
