### ISSUE TITLE
 packages updated without version upgrades 

### ISSUE THREAD

**Issue by osynge** [saltstack/salt-pack#223]
I am using [aptly](https://www.aptly.info/doc/overview/) to mirror the salt repo:

    http://repo.saltstack.com/apt/debian/8/amd64/2016.11

More than once I have found that packages have been rebuilt with the same version and a different checksum. This is the 3rd time I have seen this, and this time the offending package was:

    bsdmainutils_9.0.6_amd64.deb

I have raised a [separate bug](https://github.com/saltstack/salt-pack/issues/222) as this package is already in [jessie](https://packages.debian.org/jessie/bsdmainutils).

And the aptly error message was:

    ERROR: unable to publish: unable to process packages: error linking file to /var/lib/aptly/repo/public/salt-main/pool/main/b/bsdmainutils/bsdmainutils_9.0.6_amd64.deb: file already exists and is different

For the command:

    aptly publish switch jessie salt-main salt-main_-_2017-03-09T13:17:52Z

This is particularly bad as -
* Sites using the repo directly will not match the packages you have released and it will be difficult to diagnose this.
* Packages will not be upgraded when you provide an upgrade.
* it first blocks mirror updates for anyone using aptly mirror functionality.

To resolve this issue I would recommend you manage your salt repositories with aptly as it is the best repository management tool I have so far used with debian and a very fine program. (far better than repropro) but a simple monitoring script could be developed by you guys too.

**Comment by dmurphy18** [comment]
@osynge The issue of using reprepro is covered in https://github.com/saltstack/salt/issues/33458
where it is done for a future consideration, when time allows.

Since this is already covered by another issue, I am marking this as a duplicate.
The issue of bsdmainutils 9.0.6 was covered in issue https://github.com/saltstack/salt-pack/issues/222
and the recent release Salt 2016.3.6 was corrected.

If this satisfies your issue, can you consider closing this issue, and track  the issue of using aptly on https://github.com/saltstack/salt/issues/33458

**Comment by dmurphy18** [comment]
@osynge I am closing this since it is a duplicate. If you are unsatisfied with this, please feel free to  reopen this issue or add additional comments to saltstack/salt#33458.

Thanks for bring this issue to our attention.
