### ISSUE TITLE
Patch requirements/base.txt to use msgpack-python

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-pack#546]
The requirements file has been updated to use the renamed `msgpack`, but distributions are still deploying `msgpack-python`.  We will need to patch the requirements file during the package building to make sure that the version that the distribution uses will work correctly with salt so that python knows that the dependency has been met.

ref https://github.com/saltstack/salt/pull/47570

**Comment by dmurphy18** [comment]
There is a problem with this ref saltstack/salt#47570 since it is very platform specific, namely Redhat 7.

It can be done either way, the problem I have is a platform specific fix in a non-architecture area.  The Debian / Ubuntu family provide a virtual package for msgpack-python, whereas the latest Redhat 7 does not.  

Unsure of a better way to address it in a non-platform specific manner than patching for one or the other, but  wonder how differences in platform's naming has been handled previously for Python packages.

Just rising it to see if there is some better way to address this in the future other than patching, other than how we handle smartos and esky for Solaris 10 etc.

**Comment by dmurphy18** [comment]
Closing this since both msgpack-0.5.6.tar.gz and msgpack-python-0.5.6.tar.gz should be around for a while
