### ISSUE TITLE
Daily Ubuntu Repository does not have a Release file

### ISSUE THREAD

**Issue by icy** [saltstack/salt-pack#562]
Moved from https://github.com/saltstack/salt-bootstrap/issues/1245

### Setup

Ubuntu 16.04 with daily Saltstack repository

### Steps to Reproduce Issue

```
$ add-apt-repository -y ppa:saltstack/salt-daily
gpg: keyring `/tmp/tmp7ebt2ixh/secring.gpg' created
gpg: keyring `/tmp/tmp7ebt2ixh/pubring.gpg' created
gpg: requesting key 0E27C0A6 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp7ebt2ixh/trustdb.gpg: trustdb created
gpg: key 0E27C0A6: public key "Launchpad PPA for Salt Stack" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK

$ apt-get update
...
Ign:21 http://ppa.launchpad.net/saltstack/salt-daily/ubuntu xenial/main Translation-en_US
Ign:22 http://ppa.launchpad.net/saltstack/salt-daily/ubuntu xenial/main Translation-en
Fetched 323 kB in 16s (19.1 kB/s)
Reading package lists... Done
W: http://repo.saltstack.com/apt/ubuntu/14.04/amd64/latest/dists/trusty/InRelease: Signature by key 754A1A7AE731F165D5E6D4BD0E08A149DE57BFBE uses weak digest algorithm (SHA1)                    
W: The repository 'http://ppa.launchpad.net/saltstack/salt-daily/ubuntu xenial Release' does not have a Release file.                                                                             
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.                                                                                              
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/saltstack/salt-daily/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found                                                                   
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Versions and Systems

```
$ < /etc/os-release  grep PRETTY_NAME
PRETTY_NAME="Ubuntu 16.04.4 LTS"
```

**Comment by icy** [comment]
Thanks @dmurphy18 for your information. I have contacted Seth House on Launchpad system ( https://launchpad.net/~whiteinge). If there is any update I will let you know.

**Comment by dmurphy18** [comment]
@icy There were some issues with the automated tools packaging recently with not building internal nightly builds correctly using salt-auto-pack due to network load issues and intermittent dropping of traffic. But that occurred with Ubuntu 18.04, Ubuntu 16.04 and Debian 9 where the Release file was missing, createrepo failed to build it.  But this was all internal and never published.  PyPI was having some issue around that time with connectivity too.  Wonder if Seth may have experienced similar issues.

Currently, internally everything is working fine with additional network resources deployed.

**Comment by whiteinge** [comment]
This is partially correct. SaltStack did indeed once use Launchpad to build our official Ubuntu packages back when the community assisted us in packaging. This was several years ago before we brought our packaging in-house to the https://repo.saltstack.com/ repos. After that we stopped using Launchpad and you can see that recent builds for the listed releases are indeed quite old.

I consider that repository to be deprecated now.

@dmurphy18 if SaltStack would like access to it, I will happily add you as an administrator.

@icy that repository has always been community-run so if you are interested to put in the work to resuscitate it, you are welcome and I will add you as a member.

**Comment by dmurphy18** [comment]
@whiteinge Thanks for the offer but it is enough handling repo.saltstack.com. 

Note: Has Seth has stated,  SaltStack has not used Lauchpad in over three years for delivering packages, not since repo.saltstack.com was established.

@icy Note that there is a Debian version of Salt maintained , that ships with Debian and Ubuntu releases, for example: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=salt-minion

**Comment by dmurphy18** [comment]
@icy With the above information, can you consider this issue closed ?

**Comment by icy** [comment]
Thanks @dmurphy18  and @whiteinge for your information. If we are not using Launchpad then I think we need to remove some thing from the `salt-bootstrap` script. What do you think @rallytime ?

**Comment by dmurphy18** [comment]
@icy If there is a bootstrap issue, it would be better to have it addressed as an issue for bootstrap rather than reopening it here in salt-pack, which is for issues with packaging.  There  it will receive appropriate attention from personal working on bootstrap issues.

**Comment by rallytime** [comment]
Heh. I already had @icy move the issue from bootstrap to here. But now given the new information as discussed in this issue, it would be prudent to address this mismatch in the bootstrap script.

@icy Would you mind opening a new issue with those details in the bootstrap repo? My apologies for the run-around there.

**Comment by icy** [comment]
Ok I will discuss the issue on bootstrap project instead. :)
