### ISSUE TITLE
Debian repo only provides a single version

### ISSUE THREAD

**Issue by nicholascapo** [saltstack/salt-pack#59]
The debian repo at only provides a single package version (the latest).
This makes it very difficult to use the repo since I am forced to install the latest even though I have not yet tested it.

I need to be able to pin my package versions, so that updates can go through testing before hitting production.

**Comment by nicholascapo** [comment]
If you are using `reprepo` (which only support a single version) I recommend aptly [1] which generates repos that provide multiple versions.
I am using it to provide private internal repos, and it works great.

[1] https://www.aptly.info/

**Comment by dmurphy18** [comment]
It is working as designed, it is recommended that only the latest is provided with Debian based repo's, hence we use reprepro to generate the repositories rather than aptly.  The actual Debian maintainer for 
Salt has recommended this as the best practice,

Note on the repo.saltstack.com page tabs for various OS's are instructions for pinning to latest, major and minor versions of releases. I suggest that you pin to minor versions in rep.saltstack.com until such time you are ready to upgrade.

Given this is not going to change. I would like to close this issue, if that is okay.

**Comment by nicholascapo** [comment]
Huh, I must have missed that documentation, thank you, that solves the problem.
